# Generated by Django 4.2.28 on 2026-02-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roombooking',
            options={'ordering': ['check_in', 'created_at']},
        ),
    ]
