# Generated by Django 4.2.28 on 2026-02-13 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_roombooking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='no_of_nights',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
